version: "3"
services:
    eventStore:
        image: postgres:9.6.3
        ports:
            - 5432:5432        
        environment:
            - POSTGRES_PASSWORD=robymes.ptt
            - POSTGRES_DB=event_store